// ============================================================
// types.ts — mirrors the relevant subset of Butler's front-end
// types (apps/web/src/lib/types.ts) so the MCP server speaks the
// exact same data shapes the app already persists in IndexedDB.
// ============================================================

export type TaskStatus = "todo" | "in_progress" | "done";
export type TaskPriority = "low" | "med" | "high";

/** A task / deadline. In Butler this is a `DdlItem` in the `ddls` table.
 *  A task that carries a `dueDate` also shows up on the Calendar panel —
 *  i.e. "events" are simply tasks projected onto a date range. */
export interface Task {
  id: string;
  taskName: string;
  weight: number | null;
  dueDate: string; // YYYY-MM-DD, or "" for undated
  dueTime: string; // HH:MM, or ""
  description: string;
  isGroupWork: boolean;
  source: string;
  completed: boolean;
  notes?: string;
  status: TaskStatus;
  tags?: string[];
  priority?: TaskPriority;
  recurringId?: string; // set when generated by a workflow
}

export type RecurringCadence = "daily" | "weekly" | "monthly";

/** A workflow = a recurring-task template (Butler `RecurringTask`).
 *  Each period it materialises N task instances into `tasks`. */
export interface Workflow {
  id: string;
  taskName: string;
  cadence: RecurringCadence;
  timesPerPeriod: number;
  dueTime: string;
  weight?: number | null;
  description?: string;
  tags?: string[];
  emoji?: string;
  active: boolean;
  createdAt: number;
  lastGeneratedPeriod?: string;
}

/** A Markdown note (Butler `Note` in the `notes` table). */
export interface Note {
  id: string;
  title: string;
  content: string;
  tags?: string[];
  pinned?: boolean;
  createdAt: number;
  updatedAt: number;
}

/** Shape of the on-disk JSON vault the server reads & writes. */
export interface Vault {
  notes: Note[];
  tasks: Task[];
  workflows: Workflow[];
}
